export const dummyData = [
    {
      clientName: "Omar Ali",
      clientImage:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      transactionDetails: "#TransactionID",
      transactionTime: '12:00 AM, Jun 16, 2023',
      type: "Withdrawal",
      broker: "Perfect Money",
      walletAddress: "34ar3VW230Wfmo3214E30C2V93jmc",
      amount: "$42,324",
      assigneeName: "None",
      assigneePic:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      status: "New",
      isVerified: true,
      isApproved: false,
      isAdminApproved: true,
      isRejected: false,
    },
    {
      clientName: "Omar Ali",
      clientImage:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      transactionDetails: "#TransactionID2",
      transactionTime: '12:00 AM, Jun 16, 2023',
      type: "Deposit",
      broker: "Binance",
      walletAddress: "12xABV230Wfmo1234D32Y9gfd",
      amount: "$1,500",
      assigneeName: "None",
      assigneePic:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      status: "Assigned",
      isVerified: true,
      isApproved: false,
      isAdminApproved: true,
      isRejected: false,
    },
    {
      clientName: "Omar Ali",
      clientImage:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      transactionDetails: "#TransactionID3",
      transactionTime: '12:00 AM, Jun 16, 2023',
      type: "Withdrawal",
      broker: "Coinbase",
      walletAddress: "76hyEXW330Kwne98754TE4X9ms",
      amount: "$5,620",
      assigneeName: "None",
      assigneePic:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      status: "Unassigned",
      isVerified: true,
      isApproved: false,
      isAdminApproved: true,
      isRejected: false,
    },
    {
     clientName: "Omar Ali",
      clientImage:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      transactionDetails: "#TransactionID4",
      transactionTime: '12:00 AM, Jun 16, 2023',
      type: "Withdrawal",
      broker: "Kraken",
      walletAddress: "99yzDEW840Jknso99324WE7msd",
      amount: "$10,820",
      assigneeName: "None",
      assigneePic:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      status: "Verification",
      isVerified: true,
      isApproved: false,
      isAdminApproved: true,
      isRejected: false,
    },
    {
      clientName: "Omar Ali",
      clientImage:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      transactionDetails: "#TransactionID5",
      transactionTime: '12:00 AM, Jun 16, 2023',
      type: "Deposit",
      broker: "Gemini",
      walletAddress: "45rtFGC450Jnmne64843RA9lsx",
      amount: "$800",
      assigneeName: "None",
      assigneePic:"https://res.cloudinary.com/dam1sxczj/image/upload/v1726633543/Ellipse_85_t9dgrs.png",
      status: "Admin Verifier",
      isVerified: true,
      isApproved: false,
      isAdminApproved: true,
      isRejected: false,
    }
  ];

    